postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: todo
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - todo-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - todo-redis:/var/lib/redis/data

todo:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/todo
  ports:
    - '8000:8000'
  env_file:
    - .todo.env
