version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/todo
    command: bundle exec rails s -p 8000 -b '0.0.0.0'
    ports:
      - '8000:8000'
    env_file:
      - .todo.env
  db:
    image: postgres:9.5
    volumes:
      - todo-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  cache:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - todo-redis:/var/lib/redis/data
volumes:
  todo-db:
  todo-redis:
